### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by matmcclain**

### CODE REVIEW

**Review by matmcclain — COMMENTED** [review]
looks good

**Review by matmcclain — COMMENTED** [review]
reviewed

**Review by ryan-knopp-lilly — COMMENTED** [review]
i don't know...you suck at this pretty bad

**Review by ryan-knopp-lilly — APPROVED** [review]
ok fine...but put on the pink sombrero

**Review by ryan-knopp-lilly — APPROVED** [review]

**Review by ryan-knopp-lilly — APPROVED** [review]

**Review by matmcclain — COMMENTED** [review]
it good

**Pull request merged**
